name: test selenium python
on:
  push:
    branches:
      - main
jobs:
  test:
  
    runs-on: ubuntu-latest
    
    name: myfirstjobtest
    steps: 
      - uses: actions/checkout@v4
      - name: Run Python test with Pytest Configuration
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ensure the Pages folder has the __init__.py file
        run: |
          python -c "open('SeleniumTest/Pages/__init__.py','a').close()" x

      - name: test code execution
        run: pytest SeleniumTest/Tests/test_BasePage.py 
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
          
    
    
