name: test selenium python
on:
  push:
    branches:
      -main
  

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10","3.9","3.10","3.11","3.12","3.13"]
    name: myfirstjobtest
    steps: 
      - uses: actions/checkout@v4
      - name: Run Python test with Pytest Configuration ${{ matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
          
    
    
